// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3slhjibXbYlXV28A30gdK2Zzpyd3FfUs',
    appId: '1:680066116582:web:3a359d0450d0261d5cc427',
    messagingSenderId: '680066116582',
    projectId: 'latihan-koneksi',
    authDomain: 'latihan-koneksi.firebaseapp.com',
    storageBucket: 'latihan-koneksi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55ZGQBfYrk9jVjQpSlE9OTasUDRxLvzE',
    appId: '1:680066116582:android:9752e5cdc2af430b5cc427',
    messagingSenderId: '680066116582',
    projectId: 'latihan-koneksi',
    storageBucket: 'latihan-koneksi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04w7Dj0TY3IHFwARX5Zac69yFt5qCqho',
    appId: '1:680066116582:ios:623bb7b962dfd9e75cc427',
    messagingSenderId: '680066116582',
    projectId: 'latihan-koneksi',
    storageBucket: 'latihan-koneksi.appspot.com',
    iosClientId: '680066116582-ei56rrn0uobs63nl89h29mp7gnds4iim.apps.googleusercontent.com',
    iosBundleId: 'com.example.koneksi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04w7Dj0TY3IHFwARX5Zac69yFt5qCqho',
    appId: '1:680066116582:ios:623bb7b962dfd9e75cc427',
    messagingSenderId: '680066116582',
    projectId: 'latihan-koneksi',
    storageBucket: 'latihan-koneksi.appspot.com',
    iosClientId: '680066116582-ei56rrn0uobs63nl89h29mp7gnds4iim.apps.googleusercontent.com',
    iosBundleId: 'com.example.koneksi',
  );
}
